### ISSUE TITLE
Not working with Laravel 7.4

### ISSUE THREAD

**Issue by raphapaulino** [mnabialek/laravel-eloquent-filter#11]
`$ composer require mnabialek/laravel-eloquent-filter`

**Output:**

Using version ^0.1.1 for mnabialek/laravel-eloquent-filter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mnabialek/laravel-eloquent-filter ^0.1.1 -> satisfiable by mnabialek/laravel-eloquent-filter[v0.1.1].
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0
    - mnabialek/laravel-eloquent-filter v0.1.1 requires laravel/framework 5.* -> satisfiable by laravel/framework[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.4.0].
    - laravel/framework 5.2.x-dev conflicts with laravel/framework[v7.4.0].
    - laravel/framework 5.3.x-dev conflicts with laravel/framework[v7.4.0].
    - laravel/framework 5.4.x-dev conflicts with laravel/framework[v7.4.0].
    - Can only install one of: laravel/framework[5.0.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.1.x-dev, v7.4.0].
    - Installation request for laravel/framework (locked at v7.4.0, required as ^7.0) -> satisfiable by laravel/framework[v7.4.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by mnabialek** [comment]
I've just added support for Laravel 6 and 7. Give a try now
