### ISSUE TITLE
Trait 'App\Mnabialek\LaravelEloquentFilter\Traits\Filterable' not found

### ISSUE THREAD

**Issue by 4ndro1d** [mnabialek/laravel-eloquent-filter#2]
Following the steps in your ReadMe

**Comment by mnabialek** [comment]
Thanks for notice. You should use leading backslash. It has been just fixed in documentation

**Comment by 4ndro1d** [comment]
Offtopic: Can I use the pagination method combined with your filter?

**Comment by mnabialek** [comment]
Yes, there is no problem to do that
