### ISSUE TITLE
Multiple id's

### ISSUE THREAD

**Issue by 4ndro1d** [mnabialek/laravel-eloquent-filter#3]
_http://localhost/users?id[]=2&id=5 - should display user with id = 2 and user with id = 5_

This results in showing me entry with id = 5 only

**Comment by mnabialek** [comment]
You should try with;

```
http://localhost/users?id[]=2&id[]=5
```

instead of

```
http://localhost/users?id[]=2&id=5
```

**Comment by 4ndro1d** [comment]
Great thx, please consider updating the readme as well :)

**Comment by 4ndro1d** [comment]
One more thing: is there any best practice you can recommend from using a filter form with some inputs and select options to create the desired url?

**Comment by mnabialek** [comment]
Thanks, it has just been fixed. You can use for example PHP `http_build_query` function to do that.
