### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by 4ndro1d** [mnabialek/laravel-eloquent-filter#5]
As I was finally able to implement my needed filters using your plugin I again come across the question of pagination. On my site I got a formw ith method="get" to create my desired URL to apply the filters.
Now Laravel ships with a pagination support, which will not respect this form.

It comes with a ->appends() method on my collection, but is there any way to automate this with your plugin?

**Comment by mnabialek** [comment]
I don't know how you use it, it's possible you need to create your own paginator class that will  this

For example:

```php
$paginator = Model::filtered($yourFilter)->paginate();
$paginator->append(request()->query());
$paginator->setPath($path);
```
